"""empty message

Revision ID: ca69754ab726
Revises: 
Create Date: 2021-09-18 11:25:11.798552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca69754ab726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_published',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('date'),
    schema='admin_prototype_test'
    )
    op.create_table('dish',
    sa.Column('dish_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dish_name', sa.TEXT(), nullable=False),
    sa.Column('is_vegan', sa.BOOLEAN(), nullable=False),
    sa.Column('is_vegetarian', sa.BOOLEAN(), nullable=False),
    sa.Column('is_halal', sa.BOOLEAN(), nullable=False),
    sa.Column('is_gluten_free', sa.BOOLEAN(), nullable=False),
    sa.Column('annotation', sa.TEXT(), nullable=True),
    sa.Column('for_which_meal', postgresql.ENUM('Breakfast', 'Lunch', 'Dinner', name='meal'), nullable=False),
    sa.PrimaryKeyConstraint('dish_id'),
    sa.UniqueConstraint('dish_name'),
    schema='admin_prototype_test'
    )
    op.create_table('meal_time',
    sa.Column('meal', postgresql.ENUM('Breakfast', 'Lunch', 'Dinner', name='meal'), nullable=False),
    sa.Column('time_open', postgresql.TIME(), nullable=False),
    sa.Column('time_close', postgresql.TIME(), nullable=False),
    sa.Column('is_work_day', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('meal', 'is_work_day'),
    schema='admin_prototype_test'
    )
    op.create_table('message_of_the_day',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('message_title', sa.TEXT(), nullable=False),
    sa.Column('message_description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_prototype_test'
    )
    op.create_table('publish_version',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_prototype_test'
    )
    op.create_table('sections',
    sa.Column('section_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('section_name', sa.TEXT(), nullable=False),
    sa.Column('section_for_which_meal', postgresql.ENUM('Breakfast', 'Lunch', 'Dinner', name='meal'), nullable=False),
    sa.PrimaryKeyConstraint('section_id'),
    schema='admin_prototype_test'
    )
    op.create_table('user',
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='admin_prototype_test'
    )
    op.create_table('menu_for_meal',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('for_which_meal', postgresql.ENUM('Breakfast', 'Lunch', 'Dinner', name='meal'), nullable=False),
    sa.Column('section_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dish_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['admin_prototype_test.dish.dish_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['admin_prototype_test.sections.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_prototype_test'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_for_meal', schema='admin_prototype_test')
    op.drop_table('user', schema='admin_prototype_test')
    op.drop_table('sections', schema='admin_prototype_test')
    op.drop_table('publish_version', schema='admin_prototype_test')
    op.drop_table('message_of_the_day', schema='admin_prototype_test')
    op.drop_table('meal_time', schema='admin_prototype_test')
    op.drop_table('dish', schema='admin_prototype_test')
    op.drop_table('days_published', schema='admin_prototype_test')
    # ### end Alembic commands ###
